name: Test

on:
  push:
    branches:
      - 'dist'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Wget
        run: sudo apt install wget
      - name: Download install
        run: wget https://raw.githubusercontent.com/freescout-helpdesk/freescout/dist/tools/install.sh
      - name: chmod installer
        run: chmod u+x install.sh
      - name: Run installer
        run: sudo ./install.sh
